### ISSUE TITLE
Unable to find imports/dependencies for sass/scss files w/ nested selectors

### ISSUE THREAD

**Issue by mattpowell** [dependents/node-detective-sass#9]
For example, this returns empty:
```scss
@import "reset";
body {
  color: red;
  a {
    text-decoration: none;
  }
}
```

Passing the same thing to `gonzales-pe` causes a `ParsingError` to be thrown.

I believe this is because `node-detective-sass` isn't passing the appropriate `syntax` option to `gonzales-pe` ... will try to throw together a PR in a bit, unless there are thoughts otherwise.
